CREATE DATABASE HotalReservationSystemDB
GO

USE HotalReservationSystemDB

CREATE TABLE Hotels
(
ID INT IDENTITY(1000,1),
HotelID AS (LEFT(HotelName,3)+RIGHT('0000'+CAST(ID AS VARCHAR(4)),4)) PERSISTED,
HotelName VARCHAR(50) NOT NULL,
Country VARCHAR(30) NOT NULL,
City VARCHAR(30) NOT NULL,
HotelDescription VARCHAR(100) NOT NULL,
NoOfACRooms INT NOT NULL,
NoOfNACRooms INT NOT NULL,
RateAdultACRoom INT NOT NULL,
RateChildACRoom INT NOT NULL,
RateAdultNACRoom INT NOT NULL,
RateChildNACRoom INT NOT NULL,
CONSTRAINT PK_HotelDetails_HotelID PRIMARY KEY (HotelID)
)
GO