use HotalReservationSystemDB

CREATE TABLE Transactions
(
	TXNID INT IDENTITY(1111,1),
	ID as (CAST((RIGHT(CAST(CardNo as varchar(20)),4)+RIGHT('0000'+CAST(TXNID AS VARCHAR(4)),4))AS VARCHAR(30))) PERSISTED,
	BookingID VARCHAR(20) NOT NULL,
	CustomerID VARCHAR(5) NOT NULL,
	Amount INT NOT NULL,
	CardNo BIGINT NOT NULL,
	DateTimeOfTXN DATETIME NOT NULL,
	TXNStatus VARCHAR(10) NOT NULL,
	CONSTRAINT PK_Transactions_ID PRIMARY KEY (ID)
)
GO